[api]
api_key = "246b3f60bb878d9a34c80443fb30e963"

[email]
email_username = "kadegbie@mail.com"
email_password = "auma rvdb lxxj qukc"
smtp_server = "smtp.gmail.com"
smtp_port = 587
email_subscriber = "kadegbie@gmail.com"
