[api]
api_key = "246b3f60bb878d9a34c80443fb30e963"

[email]
email_username = "adekadegbie@mail.com"
email_password = "duam fpze qifi suuf"
smtp_server = "smtp.gmail.com"
smtp_port = 587
email_subscriber = "adekadegbie@gmail.com"
