[api]
api_key = "f730e7a01222bccf69818f1c13901936"

[email]
email_username = "adekadegbie@mail.com"
email_password = "lccs bpbn ioyw vifg"
smtp_server = "smtp.gmail.com"
smtp_port = 587
email_subscriber = "adekadegbie@gmail.com"
